{% set data = load_setup_py_data() %}

package:
  name: ts-m1m3-utils
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{PYTHON}} -m pip install --no-deps --ignore-installed .
  entry_points:

test:
  requires:
    - pytest
    - vcrpy
    - ts-conda-build =0.5
  source_files:
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - python {{python}}
    - setuptools >={{setuptools}}
    - setuptools_scm ={{setuptools_scm}}
  run:
    - python {{python}}
    - astropy
    - numpy
    - pandas
    - scipy
    - ts-xml
    - lsst-efd-client
    - ts-salobj
